title: Troubleshooting KB
description: Share some useful guides here for helping others.
theme: just-the-docs

url: https://victor-yao.github.io
baseurl: ""
permalink: pretty

aux_links:
  Repository on GitHub: https://github.com/Victor-Yao/victor-yao.github.io

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%Y-%m-%d"  # 可按需改格式
